DROP TABLE IF EXISTS Departments;
CREATE TABLE Departments (DEPARTMENT_ID INTEGER,DEPARTMENT_NAME VARCHAR(250),DIRECTOR VARCHAR(250));
CREATE INDEX Departments_KEYS ON Departments (DEPARTMENT_ID);
INSERT INTO Departments (DEPARTMENT_ID,DEPARTMENT_NAME,DIRECTOR) VALUES (1,'Sales','examples\bob');
INSERT INTO Departments (DEPARTMENT_ID,DEPARTMENT_NAME,DIRECTOR) VALUES (2,'Marketing','examples\ewilliams');

DROP TABLE IF EXISTS BudgetingAttachments;
CREATE TABLE BudgetingAttachments (EXCERCISE_ID INTEGER, ATTACHMENT_ID INTEGER AUTO_INCREMENT, MIMETYPE VARCHAR(250), FILENAME VARCHAR(250), TITLE VARCHAR(250), DESCRIPTION VARCHAR(250), CREATIONDATE TIMESTAMP, PAYLOADURL VARCHAR(250));
CREATE INDEX BudgetingAttachments_KEYS ON BudgetingAttachments (ATTACHMENT_ID);
