-- External variable database definition for H2 
-- Generated 12/11/15 1:34 PM
-- Descriptor: Metrics/Variables.xvar (currently edited)
-- External variable ExcerciseProject
DROP TABLE IF EXISTS ExcerciseProject;
CREATE TABLE ExcerciseProject (EXCERCISE_ID VARCHAR(250), DEPARTMENTID VARCHAR(250), PROJECT_ID INTEGER IDENTITY, NAME VARCHAR(250), RESPONSIBLE VARCHAR(250), TARGET_BUDGET FLOAT, NOTES VARCHAR(250), CREATED_ON TIMESTAMP, UPDATED_ON TIMESTAMP, PROCESS VARCHAR(250), PID INTEGER);
CREATE INDEX ExcerciseProject_KEYS ON ExcerciseProject (EXCERCISE_ID, DEPARTMENTID);
-- External variable ExcerciseDepartment
DROP TABLE IF EXISTS ExcerciseDepartment;
CREATE TABLE ExcerciseDepartment (EXCERCISE_ID VARCHAR(250), DEPARTMENTID VARCHAR(250), CREATED_ON TIMESTAMP, UPDATED_ON TIMESTAMP, PROCESS VARCHAR(250), PID INTEGER);
CREATE INDEX ExcerciseDepartment_KEYS ON ExcerciseDepartment (EXCERCISE_ID, DEPARTMENTID);
-- External variable BudgetingVar
DROP TABLE IF EXISTS BudgetingVar;
CREATE TABLE BudgetingVar (EXCERCISE_ID VARCHAR(250), FISCAL_YEAR INTEGER, TARGET_EXPENSES NUMERIC, EXPECTED_INCREASE NUMERIC, NEW_INVESTMENTS VARCHAR(250), TARGET_SUBMISSION TIMESTAMP, TARGET_APPROVAL TIMESTAMP, CREATED_ON TIMESTAMP, UPDATED_ON TIMESTAMP, PROCESS VARCHAR(250), PID INTEGER);
CREATE INDEX BudgetingVar_KEYS ON BudgetingVar (EXCERCISE_ID);

